language: objective-c
os: osx
osx_image: xcode9

env:
  global:
  - IOS_SCHEME="NukeWebPPlugin iOS"
    # - MACOS_SCHEME="NukeWebP macOS"
    # - TVOS_SCHEME="NukeWebP tvOS"
    # - WATCHOS_SCHEME="NukeWebP watchOS"

  matrix:
  - DESTINATION="OS=11.0,name=iPhone X"
    SCHEME="$IOS_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"
    SCHEME="$IOS_SCHEME"     RUN_TESTS="YES"
  - DESTINATION="OS=9.0,name=iPhone 5"
    SCHEME="$IOS_SCHEME"     RUN_TESTS="YES"

    # - DESTINATION="OS=10.0,name=Apple TV 1080p"
    # SCHEME="$TVOS_SCHEME"    RUN_TESTS="YES"

    # - DESTINATION="arch=x86_64"
    # SCHEME="$MACOS_SCHEME"   RUN_TESTS="YES"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

script:
  - set -o pipefail
  - carthage update --no-use-binaries --verbose
  - xcodebuild -version
  - xcodebuild -showsdks
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug | xcpretty;
    else
      xcodebuild build -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug | xcpretty;
    fi

